"""Константы приложения"""

LIMIT_LENGTH_INGREDIEN_MEASUREMENT_UNIT = 64
LIMIT_LENGTH_INGREDIENT_NAME = 128
LIMIT_LENGTH_RECIPE_NAME = 256
LIMIT_LENGTH_SHORT_CODE = 8
LIMIT_LENGTH_TAG_NAME_AND_SLUG = 32
LIMIT_LENGTH_USER_NAME = 150
PAGE_SIZE = 6
MIN_VALUE = 1
MAX_VALUE = 32000
