# Generated by Django 5.0 on 2025-05-27 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0007_ingredientrecipe_amount_alter_recipe_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientrecipe',
            name='amount',
        ),
    ]
