# Generated by Django 5.0 on 2025-05-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0009_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientrecipe',
            name='amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество'),
        ),
    ]
