# Generated by Django 5.0 on 2025-05-30 17:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0011_shoppingcart'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipe',
            unique_together={('author', 'name')},
        ),
    ]
