# Generated by Django 5.0 on 2025-05-30 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0013_alter_recipe_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipe',
            name='unique_author_name',
        ),
    ]
