# Generated by Django 5.0 on 2025-05-30 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0014_remove_recipe_unique_author_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='pub_date',
        ),
    ]
