# Generated by Django 5.0 on 2025-05-30 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0017_alter_recipe_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipe',
            unique_together=set(),
        ),
    ]
