# Generated by Django 5.0 on 2025-06-04 12:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0018_alter_recipe_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='recipes/images/', verbose_name='Изображение рецепта'),
            preserve_default=False,
        ),
    ]
