# Generated by Django 5.0 on 2025-06-17 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0021_alter_ingredientrecipe_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='short_code',
            field=models.CharField(blank=True, editable=False, max_length=3, null=True, unique=True, verbose_name='Короткая ссылка'),
        ),
    ]
