# Generated by Django 5.0 on 2025-06-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0023_alter_recipe_short_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='short_code',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=3, null=True, unique=True, verbose_name='Короткий код'),
        ),
    ]
