# Generated by Django 5.0 on 2025-06-25 11:57

import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='username',
            field=models.CharField(error_messages={'invalid': 'Допустимы только буквы, цифры и @/./+/-/_', 'max_length': 'Никнейм не должен превышать 150 символов.', 'unique': 'Этот никнейм уже занят.'}, max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator(), django.core.validators.MaxLengthValidator(150)], verbose_name='Никнейм'),
        ),
    ]
