# Generated by Django 5.0 on 2025-05-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_myuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(default='images/avatar-icon.png', null=True, upload_to='avatar/images/', verbose_name='Аватар'),
        ),
    ]
