# Generated by Django 5.0 on 2025-05-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_myuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(default='images/avatar-icon.png', null=True, upload_to='users/', verbose_name='Аватар'),
        ),
    ]
