# Generated by Django 5.0 on 2025-05-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_myuser_avatar_alter_myuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(default='images/avatar-icon.png', null=True, upload_to='users/', verbose_name='Аватар'),
        ),
    ]
