# Generated by Django 5.0 on 2025-05-24 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_myuser_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='avatar',
        ),
    ]
