# Generated by Django 5.0 on 2025-05-31 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_myuser_first_name_alter_myuser_last_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'ordering': ('username',), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
