# Generated by Django 5.0 on 2025-06-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_myuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar-icon.png', upload_to='users/', verbose_name='Аватар'),
        ),
    ]
